const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.TiledBg,
		C3.Plugins.Tilemap,
		C3.Behaviors.solid,
		C3.Plugins.Sprite,
		C3.Behaviors.Platform,
		C3.Behaviors.scrollto,
		C3.Behaviors.Timer,
		C3.Behaviors.Bullet,
		C3.Plugins.Keyboard,
		C3.Behaviors.Anchor,
		C3.Plugins.Audio,
		C3.Plugins.Camera3D,
		C3.Plugins.Text,
		C3.Plugins.Mouse,
		C3.Plugins.Spritefont2,
		C3.Plugins.TiledBg.Cnds.IsVisible,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Behaviors.Platform.Cnds.IsMoving,
		C3.Plugins.System.Acts.ScrollY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.ScrollX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Acts.SetLayoutAngle,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Behaviors.Platform.Cnds.IsOnFloor,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Keyboard.Cnds.OnKeyReleased,
		C3.Plugins.Sprite.Acts.StopAnim,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Behaviors.Platform.Acts.SimulateControl,
		C3.Behaviors.Platform.Acts.SetMaxSpeed,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Behaviors.Platform.Cnds.IsJumping,
		C3.Behaviors.Platform.Cnds.OnLand,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Behaviors.Bullet.Acts.SetAngleOfMotion,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Acts.SetEffectEnabled,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Behaviors.Bullet.Exps.AngleOfMotion,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.System.Exps.int,
		C3.Behaviors.Platform.Exps.VectorX,
		C3.Plugins.Text.Acts.SetText,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.Sprite.Cnds.CompareX,
		C3.Behaviors.Platform.Cnds.OnMove,
		C3.Behaviors.Platform.Cnds.OnStop,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.System.Acts.ResetGlobals
	];
};
self.C3_JsPropNameTable = [
	{TiledBackground: 0},
	{Solid: 0},
	{Tilemap1: 0},
	{Platform: 0},
	{ScrollTo: 0},
	{Timer: 0},
	{Bullet: 0},
	{Player: 0},
	{Keyboard: 0},
	{TiledBackground2: 0},
	{Enemy: 0},
	{Anchor: 0},
	{HP: 0},
	{SpeedBuff: 0},
	{Audio: 0},
	{Tower_Atas: 0},
	{Peluru: 0},
	{Tower_Bawah: 0},
	{Peluru_Bawah: 0},
	{BUFF_HP: 0},
	{Sprite: 0},
	{Sprite4: 0},
	{"3DCamera": 0},
	{Text: 0},
	{TiledBackground3: 0},
	{bannerb: 0},
	{bannerd: 0},
	{bannere: 0},
	{lights: 0},
	{bannera: 0},
	{bannerc: 0},
	{bannerbig: 0},
	{bannercoke: 0},
	{bannerneon: 0},
	{bannerscroll: 0},
	{bannerside: 0},
	{bannersushi: 0},
	{monitorface_preview: 0},
	{hotelsign: 0},
	{controlbox: 0},
	{bannersmall: 0},
	{banneropen: 0},
	{Sprite5: 0},
	{TiledBackground4: 0},
	{Sprite7: 0},
	{Mouse: 0},
	{Sprite8: 0},
	{SpriteFont2: 0},
	{Tower_Atas2: 0},
	{Text2: 0},
	{SpriteFont: 0},
	{antenna: 0},
	{banners: 0},
	{controlbox2: 0},
	{controlbox3: 0},
	{Tilemap2: 0},
	{NewPiskel: 0},
	{Tp: 0},
	{Text3: 0},
	{canDash: 0},
	{dashing: 0},
	{distanceScore: 0},
	{shieldHp: 0},
	{isShieldSpawned: 0},
	{bgscroll: 0}
];

self.InstanceType = {
	TiledBackground: class extends self.ITiledBackgroundInstance {},
	Tilemap1: class extends self.ITilemapInstance {},
	Player: class extends self.ISpriteInstance {},
	Keyboard: class extends self.IInstance {},
	TiledBackground2: class extends self.ITiledBackgroundInstance {},
	Enemy: class extends self.ISpriteInstance {},
	HP: class extends self.ISpriteInstance {},
	SpeedBuff: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Tower_Atas: class extends self.ISpriteInstance {},
	Peluru: class extends self.ISpriteInstance {},
	Tower_Bawah: class extends self.ISpriteInstance {},
	Peluru_Bawah: class extends self.ISpriteInstance {},
	BUFF_HP: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	_3DCamera: class extends self.IInstance {},
	Text: class extends self.ITextInstance {},
	TiledBackground3: class extends self.ITiledBackgroundInstance {},
	bannerb: class extends self.ISpriteInstance {},
	bannerd: class extends self.ISpriteInstance {},
	bannere: class extends self.ISpriteInstance {},
	lights: class extends self.ISpriteInstance {},
	bannera: class extends self.ISpriteInstance {},
	bannerc: class extends self.ISpriteInstance {},
	bannerbig: class extends self.ISpriteInstance {},
	bannercoke: class extends self.ISpriteInstance {},
	bannerneon: class extends self.ISpriteInstance {},
	bannerscroll: class extends self.ISpriteInstance {},
	bannerside: class extends self.ISpriteInstance {},
	bannersushi: class extends self.ISpriteInstance {},
	monitorface_preview: class extends self.ISpriteInstance {},
	hotelsign: class extends self.ISpriteInstance {},
	controlbox: class extends self.ISpriteInstance {},
	bannersmall: class extends self.ISpriteInstance {},
	banneropen: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	TiledBackground4: class extends self.ITiledBackgroundInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Mouse: class extends self.IInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	SpriteFont2: class extends self.ISpriteFontInstance {},
	Tower_Atas2: class extends self.ISpriteInstance {},
	Text2: class extends self.ITextInstance {},
	SpriteFont: class extends self.ISpriteFontInstance {},
	antenna: class extends self.ISpriteInstance {},
	banners: class extends self.ISpriteInstance {},
	controlbox2: class extends self.ISpriteInstance {},
	controlbox3: class extends self.ISpriteInstance {},
	Tilemap2: class extends self.ITilemapInstance {},
	NewPiskel: class extends self.ISpriteInstance {},
	Tp: class extends self.ITilemapInstance {},
	Text3: class extends self.ITextInstance {}
}